development:
  adapter: mysql2
  encoding: utf8
  database: rubys_adventure_development
  username: root
  host: localhost
  pool: 5

production:
  adapter: mysql2
  encoding: utf8
  database:
  username:
  password:
  host: localhost
  pool: 5
